import React from 'react'
import Footer from '../components/Footer'
import privacyimage from '../assets/Contact Us/privacyimage.png'

function Privacy() {
  return (
    <div>
        <div  className='privacy-background'>
                <div className='w-11/12 max-w-[1280] flex gap-16 mx-auto'>
                    <div className='w-[50%] mx-auto mt-32 heading-privacy'>
                        Cube Champs Privacy Policy
                     </div>
                     <div className='w-[50%] mx-auto mt-32'>
                        <img src={privacyimage}/>

                     </div>
                </div>  
        </div>
        <div className='w-11/12 max-w-[1280] flex flex-col gap-16 mx-auto gap-10 mt-12'>
            <div className='privacy-heading'>Updated at 2023-05-11</div>
            <div className='privacy-subheading'>
 CUBE CHAMPS LLC ("we." "our." or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by CUBE CHAMPS LLC. This Privacy Policy applies to our website, www.cubechamps.com, and its associated subdomains (collectively, our "Service"). By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
</div>
        </div>
        <div className='w-11/12 max-w-[1280] flex flex-col gap-16 mx-auto gap-10 mt-12'>
            <div className='privacy-heading'>Definitions and key terms</div>
            <div className='privacy-subheading'>
            To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:,<br></br>
 • Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.<br></br>
 • Company: when this policy mentions "Company," we," us," or "our," it refers to CUBE CHAMPS LLC, 30 North Gould Street, Suite R, Sheridan, Wyoming 82801, United States. that is responsible for your information under this Privacy Policy. <br></br>
• Country: where CUBE CHAMPS LLC or the owners/founders of CUBE CHAMPS LLC are based, in this case is INDIA.<br></br>
 • Customer: refers to the company, organization or person that signs up to use the CUBE CHAMPS LLC Service to manage the relationships with your consumers or service users.<br></br>
 • Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit CUBE CHAMPS LLC and use the services. <br></br>
• IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.<br></br>
 • Personnel: refers to those individuals who are employed by CUBE CHAMPS LLC or are under contract to perform a service on behalf of one of the parties.<br></br>
• Personal Data: any information that directly, indirectly, or in connection with other information - including a personal identification number - allows for the identification or identifiability of a natural person. <br></br>
• Service: refers to the service provided by CUBE CHAMPS LLC as described in the relative terms (if available) and on this platform. <br></br>
• Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. <br></br>
• Website: CUBE CHAMPS LLC's site, which can be accessed via this URL: www.cubechamps.com. <br></br>
• You: a person or entity that is registered with CUBE CHAMPS LLC to use the Services.<br></br>

</div>
<div className='privacy-heading'>What Information Do We Collect? </div>
<div className='privacy-subheading'>
We collect information from you when you visit our service, register, place an order, subscribe to our newsletter, respond to a survey or fill out a form. <br></br>

• Name / Username <br></br>

• Phone Numbers <br></br>

• Email Addresses <br></br>

• Mailing Addresses <br></br>

• Billing Addresses <br></br>

• Debit/credit card numbers <br></br>

• Age <br></br>

We also collect information from mobile devices for a better user experience, although these features are completely optional: <br></br>

• Location (GPS): Location data Location data helps to create an accurate representation of your interests, and this can be used <br></br>

to bring more targeted and relevant ads to potential customers. <br></br>
</div>
<div className='privacy-heading'>How Do We Use The Information We Collect? </div>
<div className='privacy-subheading'>Any of the information we collect from you may be used in one of the following ways:  <br></br>

• To personalize your experience (your information helps us to better respond to your individual needs)  <br></br>

• To improve our service (we continually strive to improve our service offerings based on the information and feedback we receive from You)  <br></br>

• To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)  <br></br>

• To process transactions  <br></br>

• To administer a contest, promotion, survey or other site feature <br></br>

• To send periodic emails </div>



<div className='privacy-heading'>When do we use customer information from third parties? </div>

<div className='privacy-subheading'>We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming our customer, we receive information from a third party that provides automated fraud detection services to us. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings</div>






<div className='privacy-heading'>Do we share the information we collect with third parties?  </div>

<div className='privacy-subheading'>We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest. <br></br>

We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and our service, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through our service. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you. <br></br>

We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the service in a shared location, and type of device used to visit the service. They may aggregate information about our advertising and what you see on the service and then provide auditing, research and reporting for us and our advertisers.  <br></br>

We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations. </div>



<div className='privacy-heading'>Where and when is information collected from customers and end users? </div>
<div className='privacy-subheading'>We will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above. </div>





<div className='privacy-heading'>How Do We Use Your Email Address?  </div>
<div className='privacy-subheading'>By submitting your email address on our service, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email. </div>






<div className='privacy-heading'>Could my information be transferred to other countries?  </div>
<div className='privacy-subheading'>We are incorporated in USA. Information collected via our website, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans-border transfer and hosting of such information. </div>






<div className='privacy-heading'>Is the information collected through our service secure?  </div>
<div className='privacy-subheading'>We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty. </div>







<div className='privacy-heading'>Can I update or correct my information? </div>
<div className='privacy-subheading'>The rights you have to request updates or corrections to the information we collect depend on your relationship with us. Personnel may update or correct their information as detailed in our internal company employment policies. Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us in order to (1) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by cancelling your account. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. To protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique password and account information at all times. You should be aware that it is not technologically possible to remove each and every record of the information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after receiving your request, all personal information stored in databases we actively use, and other readily searchable media will be updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable. If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting the organization of which you are a customer. </div>






<div className='privacy-heading'>Personnel  </div>
<div className='privacy-subheading'>If you are one of our workers or applicants, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants. You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to communications and other information you receive from us, or (3) receive a record of the information we have relating to you. Such updates, corrections, changes and deletions will have no effect on other information that we maintain. or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. </div>







<div className='privacy-heading'>Sale of Business  </div>
<div className='privacy-subheading'>We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of us or any of its Corporate Affiliates (as defined herein), or that portion of us or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy. </div>






<div className='privacy-heading'>Affiliates   </div>
<div className='privacy-subheading'>We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common control with us, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy. </div>




<div className='privacy-heading'>How Long Do We Keep Your Information?  </div>
<div className='privacy-subheading'>We keep your information only so long as we need it to provide service to you and fulfil the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we'll either remove it from our systems or depersonalize it so that we can't identify you. </div>






<div className='privacy-heading'>How Do We Protect Your Information?   </div>
<div className='privacy-subheading'>We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to us or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards. </div>






<div className='privacy-heading'>Governing Law    </div>
<div className='privacy-subheading'>The laws of USA, excluding its conflicts of law rules, shall govern this Agreement and your use of our service. Your use of our service may also be subject to other local, state, national, or international laws. </div>







<div className='privacy-heading'>Your Consent   </div>
<div className='privacy-subheading'>By using our service, registering an account, or making a purchase, you consent to this Privacy Policy. </div>







<div className='privacy-heading'>Links to Other Websites   </div>
<div className='privacy-subheading'>This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by us. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website's own rules and policies. Such third parties may use their own cookies or other methods to collect information about you. </div>



<div className='privacy-heading'>Cookies   </div>
<div className='privacy-subheading'>We use "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to personalize the Content that you see on our website. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies. </div>




<div className='privacy-heading'>Advertising   </div>
<div className='privacy-subheading'>Advertising keeps us and many of the websites and services you use free of charge. We work hard to make sure that ads are safe, unobtrusive, and as relevant as possible. </div>





<div className='privacy-heading'>Cookies for Advertising   </div>
<div className='privacy-subheading'>Cookies help to make advertising more effective. Without cookies, it's really hard for an advertiser to reach its audience, or to know how many ads were shown and how many clicks they received. </div>





<div className='privacy-heading'>Remarketing Services    </div>
<div className='privacy-subheading'>We use remarketing services. What Is Remarketing? In digital marketing, remarketing (or retargeting) is the practice of serving ads across the internet to people who have already visited your website. It allows your company to seem like they're "following" people around the internet by serving ads on the websites and platforms they use most. </div>





<div className='privacy-heading'>Kids' Privacy    </div>
<div className='privacy-subheading'>We collect information from kids under the age of 13 just to better our services. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data without your permission, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from our servers. </div>





<div className='privacy-heading'>Changes To Our Privacy Policy    </div>
<div className='privacy-subheading'>If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below. </div>




<div className='privacy-heading'>Third-Party Services   </div>
<div className='privacy-subheading'>We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services"). You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services. Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions. </div>


<div className='privacy-heading'>Facebook Pixel   </div>
<div className='privacy-subheading'>Facebook pixel is an analytics tool that allows you to measure the effectiveness of your advertising by understanding the actions people take on your website. You can use the pixel to: Make sure your ads are shown to the right people. Facebook pixel may collect information from your device when you use the service. Facebook pixel collects information that is held in accordance with its Privacy Policy. </div>



<div className='privacy-heading'>Tracking Technologies   </div>
<div className='privacy-subheading'>• Google Maps APIs <br></br>

Google Maps API is a robust tool that can be used to create a custom map, a searchable map, check-in functions, display live data synching with location, plan routes, or create a mashup just to name a few.: <br></br>

 Google Maps API may collect information from You and from Your Device for security purposes  <br></br>

Google Maps API collects information that is held in accordance with its Privacy Policyste <br></br>

• Cookies <br></br>

We use Cookies to enhance the performance and functionality of our service but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit our service as we would not be able to remember that you had logged in previously. <br></br>

• Local Storage <br></br>

Local Storage sometimes known as DOM storage, provides web apps with methods and protocols for storing client-side data. Web storage supports persistent data storage, similar to cookies but with a greatly enhanced capacity and no information stored in the HTTP request header.  <br></br>

• Sessions <br></br>

uses "Sessions" to identify the areas of our website that you have visited. A Session is a small piece of data stored on your computer or mobile device by your web browser.  </div>




<div className='privacy-heading'>Contact Us    </div>
<div className='privacy-subheading mb-20'>Don't hesitate to contact us if you have any questions. <br></br>

• Via Email: Support@cubechamps.com <br></br>

 

• Via Phone Number: +1 (307) 696-2504 </div>







        </div>


<Footer/>

    </div>
  )
}

export default Privacy